### ISSUE TITLE
Access to settings inside a entity

### ISSUE THREAD

**Issue by WebCustoms** [Webmakers/symfony-setting-bundle#1]
Hello,

I use your bundle and have a beginner question:

How can I access to a setting inside a entity?

Thank you

many Greetings

**Comment by khal3d** [comment]
Hello @richcom,

Doctrin entity is a data model and should only hold data, and you can't/shouldn't inject any service inside it.

Tell me your case and what you want to do, and I will try to help you to find the best/right way to achieve your objective.

**Comment by WebCustoms** [comment]
Hello,

Thank you for your quick response.

I have an entity called Location. Customers can book something at this location. The price is not fixed, but must be calculated. The calculation I want to make in the entity and then deploy. To calculate I need a few parameters from the SettingsBundle.

So my question.

many Greetings

Patrick

**Comment by khal3d** [comment]
You need to create a service for example call it `BookingManager`, and that service do all the calculations, and than set the final result into the entity and save to the db.

You can read more about this solutions here: http://symfony.com/doc/current/components/dependency_injection/parentservices.html
